# Stage 1: build Angular spa
FROM node:14.20 as node
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build-prod-dock


# Stage 2: serve with nginx server
FROM nginx:alpine
COPY --from=node /app/dist/TGJ-SPA /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80