version: "3.9"

services:
  tgj-api:
    build:
      context: ./TGJ-API
      dockerfile: Dockerfile.prod
    volumes:
      - ./TGJ-API:/usr/src/app
      - /usr/src/app/node_modules/ 
    ports:
      - "3001:3000"

  tgj-spa:
    build: 
      context: ./TGJ-SPA
      dockerfile: Dockerfile.prod
    volumes:
      - ./TGJ-SPA:/app # Allows image to syncronise live code changes with host pc
      - /app/node_modules/ # Excludes node_modules
    ports:
      - "5001:80"
    depends_on:
      - tgj-api